/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    cursos: Curso;
    clases: Clase;
    posts: Post;
    tags: Tag;
    users: User;
    ordenes: Ordene;
    students: Student;
    coupons: Coupon;
  };
  globals: {};
}
export interface Curso {
  id: string;
  name: string;
  description: {
    [k: string]: unknown;
  }[];
  modalidad: string;
  objetivos: {
    [k: string]: unknown;
  }[];
  temario: {
    [k: string]: unknown;
  }[];
  startDate: string;
  endDate: string;
  schedule: {
    day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
    startTime: string;
    endTime: string;
    id?: string;
  }[];
  price: number;
  tags?: string[] | Tag[];
  profesor: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface Tag {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  nombre: string;
  apellidos: string;
  telefono?: string;
  role: 'director' | 'profesor' | 'editor';
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Clase {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  curso: string | Curso;
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  tags?: string[] | Tag[];
  publishDate?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Ordene {
  id: string;
  items?: string[] | Curso[];
  total?: number;
  subtotal?: number;
  payment?: {
    name?: string;
  };
  student?: string | Student;
  coupon?: string | Coupon;
  paid?: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Student {
  id: string;
  nombre: string;
  apellidos?: string;
  telefono?: string;
  role: 'student';
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Coupon {
  id: string;
  type: 'percentage' | 'absolute';
  discount: number;
  uses: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
